#!/usr/bin/env bash
# Generate compliant RSA key pair with passphrase and strict permissions
mkdir -p ~/.ssh  # Ensure directory exists
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N "betty" -q <<<y 2>&1 >/dev/null
chmod 600 ~/.ssh/school
